version: '3.4'

services:
    mssqlserver:
        container_name: online_shop_app_db
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=1Secure*Password1

    
    reviewswebapplication:
        container_name: review_api_app
        image: review_api_app:latest
        expose:
            - "80"
        ports:
            - 7274:80
        depends_on:
            - mssqlserver
            
    onlineshopwebapp:
      container_name: online_shop_app_mvc
      image: ${DOCKER_REGISTRY-}online_shop_web_app
      build:
        context: .
        dockerfile: OnlineShopWebApp/Dockerfile
      ports:
        - 5000:80
      depends_on:
        - mssqlserver
